### PR TITLE
Update app.yaml

### PR DESCRIPTION
**Pull request by EvEkSwed**
Please make all pull requests against the **develop** branch.

### CODE REVIEW

**Comment by joostdecock** [comment]
I noticed that the translations still had the `TODO` string at the end. You can/should remove it when a string has been translated. For details, see the documentation at https://freesewing.org/docs/i18n/yaml#about-todo-and-done

It's not a big deal, and I've done it for you, I just wanted to let you know.

**Comment by joostdecock** [comment]
Oh, I also just realized that this is your first-ever pull request. So just in case that wasn't clear: You did fantastic work, and I'm really thankful 🥇

**Comment by EvEkSwed** [comment]
Hi!

I thought I did add ”DONE” to the words that I left untranslated (which were just a few, such as ”Instagram” and ”Freesewing”, I added Swedish translations along with the English computer terms that i think might be more commonly used than the Swedish terms) 🤔 
I might have missed it before I did the pull request, but then I edited. 
Should I have made a new pull request for the edited version?

By the way, I moved on to the measurements. Got confused by the first term: Across back (deprecated)
What do you mean by ”deprecated”? I haven’t heard that before and when I looked up deprecate it would mean something like ”disapprove”, which doesn’t make sence.

Best!
/Eva

**Comment by joostdecock** [comment]
No worries, it's all fine. I just wanted to avoid a misunderstanding about the use of DONE and TODO.
But you've got it all figured out, not to mention that you're doing great work :)

About the *Across back (deprecated)* entry in the measurements file, we use it in this sense:

> In several fields, deprecation is the discouragement of use of some terminology, feature, design, or practice, typically because it has been superseded or is no longer considered efficient or safe, without completely removing it or prohibiting its use. It can also imply that a feature, design, or practice will be removed or discontinued entirely in the future. (from [WikiPedia](https://en.wikipedia.org/wiki/Deprecation))

It is in this meaning of the word that we're using the term. The reason is that we used to have the `acrossBack` measurement. But because people were always measuring it wrong, we removed it from all our patterns, and switched to a different system where we use other measurements instead.

However, old drafts still have this measurement in them, so it shows up on  the website and that's why we need to have it translated.

I hope I explained that ok :)

**Comment by EvEkSwed** [comment]
Thanks! I like how you trust that I’m doing a good job even if you don’t know any Swedish at all 😂
 
I’ve translated ”deprecated” with an explanation – I’ve done the same a few times before when I think that a simple direct translation of a term would be unclear – hope that’s ok. 
The explanation in this case reads something like (isn’t used any more, but can linger in older versions).

**Comment by joostdecock** [comment]
That's perfect 🙂

I trust you. You do what you think is best 🙌

**Pull request merged**
