### PR TITLE
Option images for Sandy

### PR DESCRIPTION
**Pull request by AlfaLyr**
Please make all pull requests against the **develop** branch.

### CODE REVIEW

**Comment by joostdecock** [comment]
This is great stuff :)
We should talk about the release schedule for Sandy. We have a few options:

 - Release it ASAP marketing be damned
 - Get Romy (our illustrator) to draw a pretty picture so we can release it with more fanfare
 - Do something else

As it's your pattern, I'd like to hear what you'd like to do.

**Comment by AlfaLyr** [comment]
I don't really mind, we can do it when you want.
I was going to ask if you wanted me to draw an illustration, but if there's already an illustrator that's great, so everything is in the same style :)
If you want we can wait for the illustration, and meanwhile I can write at least the documentation for the options. I won't be able to write proper instructions yet, because I have a crazy couple of weeks at work and I'll be abroad next week, but at least something about the options since I already drew the pictures.

**Comment by joostdecock** [comment]
Ok, I'll ask Romy to draw an illustration for Sandy as soon as she's done with the one she's working on now.
Perhaps it would be useful if we have a picture of the/a similar garment. I've seen the linedrawing, and I've seen circle skirts, but the pattern illustration is supposed to show Sandy, not just any circle skirt ;)

So if you have a picture of the real thing, and how it looks on a person. Or if you could find one online that is what you as the designer had in mind, that would help :)

I've got a busy couple of weeks too, but I'll make sure to check in from time to time to make sure we keep things moving forward

**Comment by AlfaLyr** [comment]
I don't have a picture, but my idea was a "Grease style" skirt (hence the name Sandy), so I think the illustration could be cool in a kind of a pin-up style. More or less like this:
https://selectafashion.com/en/skirts/10974-rockabilly-tartan-grease-wide-skirt-belsira.html

**Comment by joostdecock** [comment]
Perfect :)

**Pull request merged**
